# =============================================================================
# Handlers - Role docker
# =============================================================================
---
- name: restart docker
  systemd:
    name: docker
    state: restarted
